version: '3.9'

services:

  backend:
    build: ./app/backend
    ports:
      - 8000:8000
    volumes:
      - ./app/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./app/frontend
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    ports:
      - 5000:4200

  db:
    image: ${SQL_IMAGE}
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: