version: '3.9'

services:

  backend:
    build: ./app/backend
    ports:
      - 8000:8000
    volumes:
      - ./app/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./app/frontend
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    ports:
      - 5000:4200